config/routes.rb
Rails.application.routes.draw do
  resources :flavor_stats
  ActiveAdmin.routes(self)
  get 'home/index'

  # root 'index#home'
  root 'home#index'
  get 'home' => 'home#index'
  
  devise_for :users
  get 'dashboard' => 'users#index'
  
  resources :beers
  resources :flavors
  resources :friendships
  
  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :users, except: [:new, :edit]
      resources :beers, except: [:new, :edit]
      resources :flavors, except: [:new, :edit]
      post 'sign_in' => 'users#sign_in'
    end
  end
end

app/models/beer.rb
class Beer < ActiveRecord::Base
    belongs_to :user
    has_many :flavors
    accepts_nested_attributes_for :flavors
    
    validates :name, presence: true
end

app/models/flavor.rb
class Flavor < ActiveRecord::Base
    belongs_to :user
    belongs_to :beer
    has_one :flavor_stat
end

app/models/flavor_stat.rb
class FlavorStat < ActiveRecord::Base
    belongs_to :flavor
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
    belongs_to :user
    belongs_to :friend, :class_name => 'User'
    
    before_create :default_status
    
    validate :validate_user_id
    validate :validate_friend_id
    
    
    
    private
    enum status: { 
        pending: 0, 
        accepted: 1 
        
    }
    
    def default_status
       self.status = :pending
    end
    
    def validate_user_id 
        errors.add(:user_id, "is invalid") unless User.exists?(self.user_id)
    end
    
    def validate_friend_id 
        errors.add(:friend_id, "is invalid") unless User.exists?(self.friend_id)
    end
    
    
    
    
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :beers
  has_many :friendships
  has_many :friends, :through => :friendships
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email, uniqueness: true
  validates :username, presence: true
    
  before_create -> { self.auth_token = SecureRandom.hex }
  
  
  def is_admin?
    self.admin
  end
  
  def self.friendable id
    where.not(id: id).where.not(id: friend_ids(id))
  end
  
  def self.friend_ids userId
    find(userId).friends.ids
  end
end

app/controllers/api/v1/beers_controller.rb
class Api::V1::BeersController < ApplicationController
  skip_before_filter :authenticate_user!
  skip_before_filter :verify_authenticity_token
  
  def create
    @beer = @current_user.beers.create! beer_params
    @beer.flavors.create! flavor_params

    render json: { success: "Added " + beer_params[:name] + "!" }
  end

  private

    def beer_params
      params.require(:beer).permit(:abv, :name, :flavors)
    end
    
    def flavor_params
      params.permit(flavors:[:name, :rating])[:flavors]
    end
end

app/controllers/api/v1/flavors_controller.rb
class FlavorsController < ApplicationController
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  skip_before_filter :authenticate_user_from_token, :only => [:create, :sign_in]
  skip_before_filter :authenticate_user!
  skip_before_filter :verify_authenticity_token

  rescue_from ActiveRecord::RecordInvalid do
    render :text => 'Ya done screwed up', :success => false, :status => :unprocessable_entity
  end
  
  
  # POST /users.json
  def create
    @user = User.create! user_params
    render json: { data: { auth_token: @user.auth_token }}
  end
  
  def sign_in
    user = User.find_by(email: user_params[:email])
      if user && user.password == user_params[:password]
        render json: { data: { auth_token: user.auth_token }}
      else
        render json: { error: 'Incorrect credentials' }, status: 401
      end
  end
  
  def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, 
      :username, :auth_token)
  end
end

app/controllers/application_controller.rb
include ActionController::HttpAuthentication::Basic::ControllerMethods
include ActionController::HttpAuthentication::Token::ControllerMethods

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!, :if => :format_html?
  before_filter :authenticate_user_from_token, :unless => :format_html?
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  def format_html?
    request.format.html?
  end
  
  def authenticate_user_from_token
    unless authenticate_with_http_token do |token, options| 
      @current_user = User.find_by(auth_token: token) 
    end
      render json: { error: 'Bad Token'}, status: 401
    end
  end
  
  def authenticate_admin_user!
    redirect_to new_user_session_path unless current_user.try(:is_admin?)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password, :remember_me) }
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  @@flavorNames = ['Hops', 'Malt', 'Other']
  
  def new
    @beer = current_user.beers.new name: "Duff"
    
    @@flavorNames.each do |flavorName|
      @beer.flavors.build name: flavorName, rating: 0
    end
  end

  def create
    @beer = current_user.beers.create! beer_params
  end
  
  def destroy
  end
  
  def show
  end 
  
  def beer_params
    params.require(:beer).permit(:id, :name, :abv, flavors_attributes: [:id, :name, :rating])
  end
  
  def update
  end
end

app/controllers/flavor_stats_controller.rb
class FlavorStatsController < InheritedResources::Base

  private

    def flavor_stat_params
      params.require(:flavor_stat).permit()
    end
end

app/controllers/flavors_controller.rb
class FlavorsController < ApplicationController
    def new
    end
    
    def update
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    
    def create
        @friendship = current_user.friendships.create! friend_id: params[:friend_id]
        @friend = User.find(@friendship.friend_id)
        puts "Friend id is #{@friendship.friend_id}"
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @friends = User.friendable current_user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/flavor_stats_helper.rb
module FlavorStatsHelper
end

app/helpers/flavors_helper.rb
module FlavorsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/beers/create.html.slim
center
    h1
        | You just entered: 
        = @beer.name

app/views/beers/new.html.slim
center 
    h1 Add Beer Data
.container      
    = bootstrap_form_for(@beer) do |b|
        = b.text_field :name
        = b.number_field :abv
        h3
            | Flavors:
        = b.fields_for :flavors do |f|
            = f.hidden_field :name
            = f.number_field :rating, label: f.object[:name]
        = b.primary
                

app/views/flavor_stats/_form.html.slim
= form_for @flavor_stat do |f|
  - if @flavor_stat.errors.any?
    #error_explanation
      h2 = "#{pluralize(@flavor_stat.errors.count, "error")} prohibited this flavor_stat from being saved:"
      ul
        - @flavor_stat.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/flavor_stats/edit.html.slim
h1 Editing flavor_stat

== render 'form'

= link_to 'Show', @flavor_stat
'|
= link_to 'Back', flavor_stats_path

app/views/flavor_stats/index.html.slim
h1 Listing flavor_stats

table
  thead
    tr
      th
      th
      th

  tbody
    - @flavor_stats.each do |flavor_stat|
      tr
        td = link_to 'Show', flavor_stat
        td = link_to 'Edit', edit_flavor_stat_path(flavor_stat)
        td = link_to 'Destroy', flavor_stat, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Flavor stat', new_flavor_stat_path

app/views/flavor_stats/new.html.slim
h1 New flavor_stat

== render 'form'

= link_to 'Back', flavor_stats_path

app/views/flavor_stats/show.html.slim
p#notice = notice


= link_to 'Edit', edit_flavor_stat_path(@flavor_stat)
'|
= link_to 'Back', flavor_stats_path

app/views/friendships/create.html.slim
center
    h1 
        = "You just friended #{@friend.username}"

app/views/users/index.html.slim
.container

    .container.jumbotron
        center
            h1
                | Yer in the dashboard, mate!
            
    = link_to "Add a Beer", new_beer_path, class: "btn btn-lg btn-default pull-right"
    
.container
    - if current_user.beers.size == 0
        center
            h3
                | No beers have been added.  Why don't you 
                =link_to "add one now!", new_beer_path
    - else
        h3
            | Your Beers:
            ul
                - current_user.beers.each do |beer|
                    .list-group-item.braveheart
                        = beer.name
                        .text-right
                            = beer.abv
                            - flavors = beer.flavors
                            - flavors.each do |flavor|
                                = flavor.name
                                = flavor.rating
                                
                  
.container
    h3
        | Friends:
        - for friend in @friends
            .list-group-item.friend
                p
                    strong 
                        =h friend.username
                    = link_to " Add Friend", friendships_path(:friend_id => friend), :method => :post
                    .clear